//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RszTool.App.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RszTool.App.Resources.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Component 的本地化字符串。
        /// </summary>
        internal static string Component {
            get {
                return ResourceManager.GetString("Component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duplicate 的本地化字符串。
        /// </summary>
        internal static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duplicate many times 的本地化字符串。
        /// </summary>
        internal static string DuplicateMulti {
            get {
                return ResourceManager.GetString("DuplicateMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Field name 的本地化字符串。
        /// </summary>
        internal static string FieldName {
            get {
                return ResourceManager.GetString("FieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Field value 的本地化字符串。
        /// </summary>
        internal static string FieldValue {
            get {
                return ResourceManager.GetString("FieldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File 的本地化字符串。
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File is changed, do you want to save it? 的本地化字符串。
        /// </summary>
        internal static string FileChangedPrompt {
            get {
                return ResourceManager.GetString("FileChangedPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find GameObjects 的本地化字符串。
        /// </summary>
        internal static string FindGameObjects {
            get {
                return ResourceManager.GetString("FindGameObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find instances 的本地化字符串。
        /// </summary>
        internal static string FindInstances {
            get {
                return ResourceManager.GetString("FindInstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GameObject Name 的本地化字符串。
        /// </summary>
        internal static string GameObjectName {
            get {
                return ResourceManager.GetString("GameObjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Include Children 的本地化字符串。
        /// </summary>
        internal static string IncludeChildren {
            get {
                return ResourceManager.GetString("IncludeChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input class name 的本地化字符串。
        /// </summary>
        internal static string InputClassName {
            get {
                return ResourceManager.GetString("InputClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input duplicate count 的本地化字符串。
        /// </summary>
        internal static string InputDulicateCount {
            get {
                return ResourceManager.GetString("InputDulicateCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Match Case 的本地化字符串。
        /// </summary>
        internal static string MatchCase {
            get {
                return ResourceManager.GetString("MatchCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Match Whole Word 的本地化字符串。
        /// </summary>
        internal static string MatchWholeWord {
            get {
                return ResourceManager.GetString("MatchWholeWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message 的本地化字符串。
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New item 的本地化字符串。
        /// </summary>
        internal static string NewItem {
            get {
                return ResourceManager.GetString("NewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not supported file format 的本地化字符串。
        /// </summary>
        internal static string NotSupportedFormat {
            get {
                return ResourceManager.GetString("NotSupportedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste after 的本地化字符串。
        /// </summary>
        internal static string PasteAfter {
            get {
                return ResourceManager.GetString("PasteAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste Gameobject 的本地化字符串。
        /// </summary>
        internal static string PasteGameobject {
            get {
                return ResourceManager.GetString("PasteGameobject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste Gameobject as child 的本地化字符串。
        /// </summary>
        internal static string PasteGameobjectAsChild {
            get {
                return ResourceManager.GetString("PasteGameobjectAsChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quit 的本地化字符串。
        /// </summary>
        internal static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove 的本地化字符串。
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reopen 的本地化字符串。
        /// </summary>
        internal static string Reopen {
            get {
                return ResourceManager.GetString("Reopen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} not found, please copy it from RE_RSZ manually 的本地化字符串。
        /// </summary>
        internal static string RszJsonNotFound {
            get {
                return ResourceManager.GetString("RszJsonNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save as 的本地化字符串。
        /// </summary>
        internal static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tag 的本地化字符串。
        /// </summary>
        internal static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open a file from the file menu or drag it in .
        ///Currently, user, scn, pfb files are supported 的本地化字符串。
        /// </summary>
        internal static string UsageHint {
            get {
                return ResourceManager.GetString("UsageHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Regular Expression 的本地化字符串。
        /// </summary>
        internal static string UseRegex {
            get {
                return ResourceManager.GetString("UseRegex", resourceCulture);
            }
        }
    }
}
